// basic ops
(print-num (+ 8 9))
(print-num (+ (- 8 -7) 9))
(print-num (* 8 9 0))
(print-num (- 8 9))
(print-num (mod 9 8))
(print-num (mod 9 9))
(print-num (/ 9 8))
(print-num (/ 9 9))
(print-bool (> 3 2))
(print-bool (< 3 2))
(print-bool (or #t #f #f #f))
(print-bool (and #t #f #t #f))
(print-bool (and #t #t #t #t))
(print-bool (not #t))
(print-bool (= 10 10 10))